DJANGO/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^pointqanalysis/', include('pointqanalysis.urls', namespace='pointqanalysis', app_name='pointqanalysis')),
    url(r'^admin/', include(admin.site.urls)),
)

DJANGO/mysite/pointqanalysis/urls.py
from django.conf.urls import patterns, url

from pointqanalysis import views

urlpatterns = patterns('',
    url(r'^$', views.analysis, name='analysis'),
    url(r'^simulations$', views.simul_manag, name='simulations'),
    url(r'^uploadxml$', views.upload_xml, name='upload_xml'),
    url(r'^ajax', views.ajax, name='ajax'),
    url(r'^vehtraj', views.vehtraj, name='vehtraj'),
    url(r'^dashboard', views.dashboard, name='dashboard')
)

DJANGO/mysite/pointqanalysis/forms.py
from django import forms
from .tools import tools_data

def validate_file_extension(value):
	if not value.name.endswith('.txt'):
		raise forms.ValidationError(u'Error: Wrong file extension')

def get_my_choices():

	# we create the table index_network if it's not created
    #	query_1 = 'CREATE TABLE index_network (name text, geojson text)'
	query_1 = 'CREATE TABLE index_network (name text, geojson text, topjson text)'
	tools_data.query_sql([query_1], False, 'network_db')

	query_2 = 'SELECT name FROM index_network'
	output = tools_data.query_sql([query_2], True, 'network_db')
	liste_name = []
	for line in output:
		liste_name.append((line['name'], line['name']))
	
	return liste_name
        
class Form_upload_fil (forms.Form):

	def __init__(self, *args, **kwargs):
		super(Form_upload_fil, self).__init__(*args, **kwargs)

		# creates a tuple of the available networks
		self.fields['name_network'] = forms.ChoiceField(choices=get_my_choices())

	name_simul = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name Simulation', 'class': 'form-control'}))
	description_simul = forms.CharField(max_length=140, widget=forms.Textarea(attrs={'placeholder': 'Description Simulation', 'class': 'form-control', 'rows': 4}))
	simul_txt_db = forms.FileField(validators=[validate_file_extension])
    
class Form_upload_xml (forms.Form):
	name_network = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name Network', 'class': 'form-control'}))
	network_xml = forms.FileField()

class Form_delete_xml (forms.Form):

	def __init__(self, *args, **kwargs):
		super(Form_delete_xml, self).__init__(*args, **kwargs)

		# creates a tuple of the available networks
		choices=get_my_choices()
		choices.append(('',''))
		self.fields['name_network_delete'] = forms.ChoiceField(choices)

DJANGO/mysite/pointqanalysis/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from .forms import Form_upload_fil,  Form_upload_xml , Form_delete_xml
from django.conf import settings
import json
import os
import re
import time
import sqlite3
import gzip
from pointqanalysis.tasks import birdeye, birdeye_micro
from tools import tools_data, tools_json, tools_sql



###################################################################################################################
###                                                                    VIEWS					   			   ###
###################################################################################################################

@csrf_exempt
def ajax(request):
	if request.method == 'POST':
		if request.POST.get("action", "") == 'veh_trajectory':
			links = json.loads(request.POST.get("links", ""))
			max_nb_veh = json.loads(request.POST.get("max_nb_veh", ""))
			id_route_analyse = json.loads(request.POST.get("id_route_analyse", ""))
			tmin_analysis = json.loads(request.POST.get("tmin_analysis", ""))
			tmax_analysis = json.loads(request.POST.get("tmax_analysis", ""))

			# First we calculate the length of each link
			try:
				sim_name = request.COOKIES['sim_name']
				# which network is associated with the simulation
				query_1 = 'SELECT name_network FROM index_simul_network WHERE name_simul = \'' + str(sim_name) + '\''
				associated_network = tools_data.query_sql([query_1], True, 'network_db')[0]['name_network']
				
				result = tools_sql.plot_vehicle_traj(links[0], links[len(links) - 1], tmin_analysis, tmax_analysis, id_route_analyse, max_nb_veh, sim_name, "pointq_db", associated_network)

				return HttpResponse(json.dumps(result))
			except:
				return HttpResponse('False')

		elif request.POST.get("action", "") == 'stage_actuation':
			nodes_plotted = json.loads(request.POST.get("nodes_plotted", ""))
			sim_name = request.COOKIES['sim_name']
			dic_node_stage_actuation = {}

			for node in nodes_plotted:
				# which network is associated with the simulation
				query_1 = 'SELECT ev_time, int_ctrl_mat FROM \'' + str(sim_name) + '\' WHERE ev_type = 3 AND id_inter = '+ str(node)
				stage_actuation_node = tools_data.query_sql_debug([query_1], True, 'pointq_db')
				dic_node_stage_actuation[str(node)] = stage_actuation_node

			return HttpResponse(json.dumps(dic_node_stage_actuation))

		elif request.POST.get('action', '') == 'bird_traj':
			try : 
				sim_name = request.COOKIES['sim_name']
				conf = json.loads(request.POST.get("conf", ""))

				conn = sqlite3.connect(os.path.join(settings.BASE_DIR, 'network_db.sqlite3'))
				c = conn.cursor()
				c.execute('SELECT bird_occupation FROM index_simul_network WHERE name_simul = \'' + sim_name + '\'')
				result = c.fetchone()
				occupation = result[0]
				vehicles = tools_json.birdeye_filter(sim_name, conf)

				conn.close()
				if vehicles == 'False' or occupation == 'False':
					bird_traj = '{"vehicles":false, "occupation": false}'
				else:
					bird_traj = '{"vehicles":' + json.dumps(vehicles) + ', "occupation": ' + occupation + '}'

				bird_traj = bird_traj.encode('utf-8')
				bird_traj = gzip.compress(bird_traj)
			except:
				bird_traj = 'Error while querying the database'
				bird_traj = gzip.compress(bird_traj)

			response = HttpResponse(bird_traj)
			response['Content-Encoding'] = 'gzip'
			return response

	else:

		if request.GET.get('action', '') == 'deltable':
			table = request.GET.get('table_name', '')
			return HttpResponse(tools_sql.deltable(table))

		elif request.GET.get('action', '') == 'set_cookie':
			sim_name = request.GET.get('sim_name', '')
			response = HttpResponse('Cookie')
			response.set_cookie(key = 'sim_name', value = sim_name)
			return response

		elif request.GET.get('action', '') == 'redirect':
			redirection = request.GET.get('redirection', '')
			return HttpResponse(reverse('pointqanalysis:' + redirection))

		elif request.GET.get('action', '') == 'get_from_node':
			node_id = request.GET.get('node_id', '')
			type_anal = request.GET.get('type', '')
			if type_anal == 'flow':
				answer = tools_json.json_get_output_links(node_id)
			return HttpResponse(json.dumps(answer,indent=4), content_type="application/json")

		elif request.GET.get('action', '') == 'list_vehicle_traj':
			ori_link = request.GET.get('ori_link', '')
			dest_link = request.GET.get('dest_link', '')
			sim_name = request.COOKIES['sim_name']
			answer = tools_sql.list_vehicle_traj(ori_link, dest_link, sim_name, 'pointq_db')
			dic_routes = answer[0]
			time =  answer[1]
			output = [[list(x), dic_routes[x][0], dic_routes[x][1]] for x in  dic_routes.keys()]
			json_output = json.dumps({'routes': output, 'time': time})
			return HttpResponse(json_output, content_type="application/json")

		elif request.GET.get('action', '') == 'generate_json_plot':
			# we treat the parameters
			type_anal = request.GET.get('type', '')
			t_start = int(request.GET.get('t_start', ''))
			t_end = int(request.GET.get('t_end', ''))
			sim_name = request.COOKIES['sim_name']
			# first case: flows
			if type_anal == 'flow':
				granul = int(request.GET.get('granul', ''))
				links = request.GET.get('links', '')
				list_links = links.split('-')
				data = []

				# which network is associated with the simulation
				query_1 = 'SELECT name_network FROM index_simul_network WHERE name_simul = \'' + str(sim_name) + '\''
				associated_network = tools_data.query_sql([query_1], True, 'network_db')[0]['name_network']

				# get the top_json associated with the simulation
				query_2 = 'SELECT topjson FROM index_network WHERE name = \'' + str(associated_network) + '\''
				topjson = tools_data.query_sql([query_2], True, 'network_db')[0]['topjson']

				for link_id in list_links:
					data.append(tools_json.json_plot_flow(link_id, t_start, t_end, granul, sim_name, topjson))

				title = {'text': 'Flows'}
				axisX = {'title': "Time interval [s]", 'titleFontWeight': "lighter", 'titleFontSize': '17'}
				axisY = {'title': "Flow [veh per interval]", 'titleFontWeight': "lighter", 'titleFontSize': '17'}
				answer = {'title': title, 'exportEnabled': 'true', 'axisX': axisX, 'axisY': axisY, 'data': data}
				return HttpResponse(json.dumps(answer, indent=4), content_type="application/json")

			# second case : queues
			elif type_anal == 'queue':
				link_occupancy = request.GET.get('link_occupancy', '')
				sep_queues_origin = request.GET.get('sep_queues_origin', '')
				queues = request.GET.get('queues', '')
				list_queues = queues.split('-')
				queues_occupancy = {}
				queues_origin = []

				list_queues_treated = []
				for queue in list_queues:
					list_queues_treated.append('[' + queue.split('.')[0] + ', ' + queue.split('.')[1] + ']')

				if link_occupancy == 'true':
					list_first_link = []
					for queue in list_queues_treated:
						list_first_link.append(queue.split(',')[0][1:])

					list_first_link_occupancy = set()
					for first_link in list_first_link:
						if (list_first_link.count(first_link) > 1):
							list_first_link_occupancy.add(first_link)

					for link in list_first_link_occupancy:
						queues_occupancy[link] = []

					for queue in list_queues_treated:
						first_link = queue.split(',')[0][1:]
						second_link = int(queue.split(',')[1][:-1])
						if first_link in list_first_link_occupancy:
							queues_occupancy[first_link].append(second_link)

					# we delete keys of queues occupancy from list_queus treated
					# queues_occupancy -> we want to plot the total occupancy of a link
					# list_queues_treated -> we want to plot independant queues
					
					list_queues_treated = [x for x in list_queues_treated if x.split(',')[0][1:] not in queues_occupancy.keys()]

				elif sep_queues_origin == 'true':
					# we reset list_queues_treated
					list_queues_treated = []

					# we create the string to plot queues without any separation
					for queue in list_queues:
						list_queues_treated.append('[' + queue.split('.')[1] + ', ' + queue.split('.')[2] + ']')

					# we create an array to plot origin based separated queues
					for queue in list_queues:
						temp = []
						temp.append(queue.split('.')[0])
						temp.append(queue.split('.')[1])
						temp.append(queue.split('.')[2])
						queues_origin.append(temp)

				data = []

				# we generate the plots for independant queues
				for queue in list_queues_treated:
					data.append(tools_json.json_plot_queue(queue, t_start, t_end, sim_name))

				# we generate the plots for the total occupancy of links
				if link_occupancy == 'true':
					list_series = tools_json.json_plot_link_occupancy(queues_occupancy, t_start, t_end, sim_name)

					for serie in list_series:
						data.append(serie)

				# we generate the plots for origin based queues
				if sep_queues_origin == 'true':
					for queue in queues_origin:
						data.append(tools_json.json_plot_queue_origin(queue, t_start, t_end, sim_name))

				title = {'text': 'Queues'}
				axisX = {'title': "Time [s]", 'titleFontWeight': "lighter", 'titleFontSize': '17'}
				axisY = {'title': "Queue length [veh]", 'titleFontWeight': "lighter", 'titleFontSize': '17'}
				answer = {'zoomEnabled': 'true', 'exportEnabled': 'true', 'title': title, 'axisX': axisX, 'axisY': axisY, 'data': data}
				return HttpResponse(json.dumps(answer, indent=4), content_type="application/json")
			#last case :  ODs
			elif type_anal == 'OD':
				pairs = request.GET.get('ODs', '')
				list_pairs = pairs.split('-')
				list_pairs_treated = []
				for pair in list_pairs:
					list_pairs_treated.append(pair.split('.'))

				data=[]
				for pair in list_pairs_treated:
					data.append(tools_json.json_plot_TT(int(pair[0]), int(pair[1]), t_start, t_end, sim_name))
				title = {'text': 'Travel Time'}
				axisX = {'title': "Entry Time [s]", 'titleFontWeight': "lighter", 'titleFontSize': '17'}

DJANGO/mysite/pointqanalysis/templates/pointqanalysis/template_skeleton.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'pointqanalysis/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Add custom CSS here -->
    <link href="{% static 'pointqanalysis/css/logo-nav.css' %}" rel="stylesheet">
    <link href="{% static 'pointqanalysis/css/zoombox.css' %}" rel="stylesheet">
    <link href="{% static 'pointqanalysis/css/slider.css' %}" rel="stylesheet">
    {% block css %} {% endblock %}
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="{% static 'pointqanalysis/images/logo.gif' %}" alt="">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                {% if sim_name %}
                    <li class"dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{sim_name}}<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href={% url 'pointqanalysis:simulations' %}>Change Simulation</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <a href={% url 'pointqanalysis:simulations' %}>Simulations</a>
                    </li>
                {% endif %}
                    <li class"dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Analysis<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href={% url 'pointqanalysis:dashboard' %}>Dashboard</a></li>
                            <li><a href={% url 'pointqanalysis:analysis' %}>General Analysis</a></li>
                            <li><a href={% url 'pointqanalysis:vehtraj' %}>Vehicles Trajectories</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="http://point-q-documentation.readthedocs.org/" target="_blank">Documentation</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>

    <div class="container">
        {% block container %} {% endblock %}
    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    {% block javascript %} {% endblock %}
</body>

</html>

DJANGO/mysite/pointqanalysis/templates/pointqanalysis/upload.html
{% extends 'pointqanalysis/template_skeleton.html' %}
{% load staticfiles %}
{% block title %}Simulations{% endblock %}

{% block css %} 
	<link href="{% static 'pointqanalysis/css/jquery.dynatable.css' %}" rel="stylesheet">
{% endblock %}

{% block container %} 
	<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="linkoccupancyModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title" id="queueModalLabel">Delete</h4>
				</div>
				<div class="modal-body">
					Please confirm that you want to delete the simulation from the database
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary confirm_delete">DELETE</button>
				</div>
			</div>
		</div>
	</div>
	<div style="margin-bottom: 100px">
		<h2>Available simulations:</h2>
		<!-- <ul class="no_puce">
		</ul> -->

		<table id="table_simul" class="table table-bordered">
			<thead>
				<th>Name</th>
				<th>Description</th>
				<th>Date</th>
				<th>Associated Network</th>
				<th>Select</th>
				<th>Delete</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
	<div>
		<h2>Upload a simulation:</h2>
		{% if status != '' %}
			<div id='status'>
				<p>{{ status}}</p>	
			</div>
		{% endif %}

		{% if form.errors %}
			<p class="error_red">
				Please correct the error{{ form.errors|pluralize }} below:
			</p>
		{% endif %}

		<form role="form" enctype="multipart/form-data" action="" method="post">{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="form-group">
				<label for="id_name_simul">Name Simulation:</label>
				{{ form.name_simul.errors }}
				{{ form.name_simul }}
			</div>
			<div class="form-group">
				<label for="id_description_simul">Description Simulation:</label>
				{{ form.description_simul.errors }}
				{{ form.description_simul }}
			</div>
			<div class="form-group">
				<label for="id_simul_txt_db">Select Simulation:</label>
				{{ form.simul_txt_db.errors }}
				{{ form.simul_txt_db }}
			</div>
			<div class="form-group">
				<label for="id_name_network">Network:</label><br />
				{{ form.name_network.errors }}
				{{ form.name_network}}
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
		<p>
			<br /><br />
			<a href= {{upload_xml}} class="zoombox" >Click here to upload /delete networks</a><br />
		</p>
	</div>
{% endblock %}

{% block javascript %} 
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'pointqanalysis/js/zoombox.js' %}"></script>
	<script type="text/javascript" src="{% static 'pointqanalysis/js/jquery.dynatable.js' %}"></script>
	<script type="text/javascript"  src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script type="text/javascript">
		jQuery(function($){
			$('a.zoombox').zoombox({width: 900, height: 500});
		});
	</script>

	{% if status != '' %}
		<script type="text/javascript">
			$( "#status" ).fadeOut(10000);
		</script>
	{% endif %}
	
	<script type="text/javascript">

		/*
		*  Escape newline chars for being transmitted with JSON over the wire
		*/
		function escapeNewLineChars(valueToEscape) {
			if (valueToEscape != null && valueToEscape != "") {
				return valueToEscape.replace(/\n/g, "\\n");
				console.log('Cool');
			}
			else {
				console.log('not_cool');
				return valueToEscape;
			}
		}

		/*
		*  Converts \n newline chars into <br> chars s.t. they are visible
		*  inside HTML
		*/
		function convertToHTMLVisibleNewline(value) {
			if (value != null && value != "") {
				return value.replace(/\n/g, "<br/>");
			} 
			else {
				return value;
			}
		}
		
		var json_simulations = '{{ json_simulations|safe }}';
		console.log(json_simulations);
		json_simulations = JSON.parse(json_simulations);

		for (var i = 0; i < json_simulations.length; i++) {
			json_simulations[i]['select'] = "<button type='button' class='btn btn-default btn-xs analyse'>Analyse</button>";
			json_simulations[i]['delete'] = "<button type='button' class='btn btn-default btn-xs delete'>Delete</button>";
		}

		$('#table_simul').dynatable({
			dataset: {
				records: json_simulations
			}
		});

		$('table').on('click', '.analyse',function(){
			var sim_selected = $(this).parents().eq(1).children(":first").text();
			$.ajax('../pointqanalysis/ajax?action=set_cookie&sim_name=' + sim_selected);
			$.ajax('../pointqanalysis/ajax?action=redirect&redirection=analysis').done(function(url){
				window.location.replace(url);
			});
		});

		var simu_2_delete = '';
		$('table').on('click', '.delete',function(){
			simu_2_delete = $(this).parents().eq(1).children(":first").text();
			$('#deleteModal').modal();
			$('.confirm_delete').click(function(event){
				event.stopPropagation();
				console.log("Click");
				$.ajax('../pointqanalysis/ajax?action=deltable&table_name=' + simu_2_delete).done(function(){
					location.reload();
				});

			});
		});

	</script>
{% endblock %}

DJANGO/mysite/pointqanalysis/templates/pointqanalysis/uploadxml.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Upload network</title>

		<!-- Bootstrap core CSS -->
		<link href="{% static 'pointqanalysis/css/bootstrap.min.css' %}" rel="stylesheet">

		<!-- Add custom CSS here -->
		<style type="text/css"> 
			html {
				min-width: 100%;
				min-height: 100%;
			}

			body {
				width: 850px;
				height: 250px;
			}
		</style> 
	</head>

	<body>
	<div style="padding: 40px; width: 750px; height: 250px;">
		<h2>Upload a network</h2>
		<form role="form" enctype="multipart/form-data" action="" method="post" status = "{{ status }}" id = "form_xml">{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="form-group">
				<label for="id_name_network">Name Network:</label>
				{{ form.name_network.errors }}
				{{ form.name_network }}
			</div>
			<div class="form-group">
				<label for="id_network_xml">Select network:</label>
				{{ form.network_xml.errors }}
				{{ form.network_xml }}
			</div>
			<button type="submit" class="btn btn-default" id = "submit_xml">Upload</button>
		</form>
		<br />
		<h2>Delete a network</h2>
		<form role="form" enctype="multipart/form-data" action="" method="post"  status = "{{ status }}"  id = "form_xml_delete">{% csrf_token %}
			{{ form2.non_field_errors }}
			<div class="form-group">
				<label for="id_name_network_delete">Network:</label><br />
				{{ form2.name_network_delete.errors }}
				{{ form2.name_network_delete}}
			</div>
			<button type="submit" class="btn btn-default" id = "submit_xml">Delete</button>
		</form>
	</div>

	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script type="text/javascript">
		$(function(){

			if ($('#form_xml').attr('status') == 'posted') {
				parent.location.reload(true);
				parent.$.zoombox.close();	
				
			}

			else if ($('#form_xml_delete').attr('status') == 'posted') {
				parent.location.reload(true);
				parent.$.zoombox.close();	
				
			}
		});
	</script>
	</body>
</html>